os: linux
dist: xenial
language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
install:
 - pip install coveralls
before_script:
  - sudo apt-get update -y
  - sudo apt-get install -y libsoundio-dev
script:
  - coverage run --source pysoundio setup.py test
after_success:
  coveralls